In [19]:
# import necessary libraries
import numpy as np
import rasterio as rio
from rasterio.plot import show
import folium as fl
import matplotlib.pyplot as plt
# task: read a raster file (Data: Sentinel-2) and perform an index calculation
# the calculated index wil be the cholorphyl vegetation index (CVI) 
# the instructions to this index can be found at https://www.indexdatabase.de/db/i-single.php?id=391

# for this script, the necessary data are stored locally on the machine


In [39]:
# data can be found at https://browser.dataspace.copernicus.eu/?zoom=9&lat=38.44897&lng=66.93311&themeId=DEFAULT-THEME&visualizationUrl=U2FsdGVkX18wEuUwqWryjONcimFkAuyOmkGwRNrXfvUXR44a7bE2gtbe1tXdmx8Y0z6q3i3NJvwG25o83YxierXMsqk7hG68Np%2BCp5LACOYARUPfOPjU9hOgdE7bxLct&datasetId=S2_L2A_CDAS&fromTime=2025-06-02T00%3A00%3A00.000Z&toTime=2025-06-02T23%3A59%3A59.999Z&layerId=1_TRUE_COLOR
# or in this repo in the data folder

with rio.Env():
    with rio.open("data/B04.tif") as red, rio.open("data/B08.tif") as nir:
        r1 = red.read(1)
        nir1 = nir.read(1)
        
        ndvi = ((nir1 - r1) / (nir1 + r1))
        print(nir1)
        print(r1)
        print(np.info(r1))
        print(np.info(nir1))
        print(np.info(ndvi))
        
    #     # write to a new file
    #     with rio.open("data/ndvi.tif", "w", driver="GTiff", width=r1.shape[1], height=r1.shape[0], count=1, dtype=r1.dtype, crs=red.crs, transform=red.transform) as dst:
    #         dst.write(ndvi, 1)
            
    #     # read the new file and display it
    #     with rio.open("data/ndvi.tif") as dst:
    #         r2 = dst.read(1)
    
    # # load data, extract bands, compare maps in leaflet or something similar. 
    
    
    
    
    

[[3450 3526 3530 ... 4556 4432 4408]
 [3502 3522 3494 ... 4616 4532 4500]
 [3488 3518 3510 ... 4644 4604 4596]
 ...
 [4836 4852 5060 ... 3770 3864 3810]
 [4924 4736 4980 ... 3610 3786 3764]
 [4748 4812 5012 ... 3440 3510 3564]]
[[2588 2564 2604 ... 4030 3978 3912]
 [2542 2504 2560 ... 4140 4056 4022]
 [2556 2466 2498 ... 4136 4090 4074]
 ...
 [2704 2806 3850 ... 3388 3474 3472]
 [3248 2772 3532 ... 3230 3320 3374]
 [3578 2792 3104 ... 3092 3120 3216]]
class:  ndarray
shape:  (10980, 10980)
strides:  (21960, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x17f01726040
byteorder:  little
byteswap:  False
type: uint16
None
class:  ndarray
shape:  (10980, 10980)
strides:  (21960, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x17f912ee040
byteorder:  little
byteswap:  False
type: uint16
None
class:  ndarray
shape:  (10980, 10980)
strides:  (87840, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 

In [3]:
with rio.Env():
    with rio.open(r"/data/T42SUG_20240727T061631_B04_10m.jp2") as red:
        print(red)

RasterioIOError: '/data/T42SUG_20240727T061631_B04_10m.jp2' does not exist in the file system, and is not recognized as a supported dataset name.